apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
        - 2001:1234:5678:9a40::/58
    services:
      cidrBlocks:
        - 10.0.0.0/16
        - fd00::/108
